version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - checkout
      - run: sudo composer self-update --1
      - restore_cache:
          key: composer-v1-{{ checksum "composer.lock" }}      
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor    
      - restore_cache:
          key: npm-v1-{{ checksum "package-lock.json" }} 
      - run:
          name: npm ci
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi 
      - save_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules                      
      - run: npm run dev
      - run:
          name: php test
          command: vendor/bin/phpunit
          
  deploy:
    docker:
      - image: circleci/php:7.3-node-browsers
  # ここからはCodeDeploy使用時に追加
    environment:
      AWS_DEFAULT_REGION: ap-northeast-1
  # ここまではCodeDeploy使用時に追加
    steps:
  # ここからはCodeDeploy使用時は削除
      # - add_ssh_keys
      # - run:
      #     name: deploy
      #     command: |
      #       ssh -o StrictHostKeyChecking=no -t webapp2@${HOST_NAME} "cd laravel-ci && \
      #         git pull origin master && \
      #         composer install -n --no-dev --prefer-dist && \
      #         npm ci && \
      #         npm run prod && \
      #         php artisan migrate --force && \
      #         php artisan config:cache"
  # ここまではCodeDeploy使用時は削除
  # ここからはCodeDeploy使用時に追加
      - checkout
      - run: sudo composer self-update --1
      - restore_cache:
          key: composer-no-dev-v1-{{ checksum "composer.lock" }}
      - run: composer install -n --no-dev --prefer-dist
      - save_cache:
          key: composer-no-dev-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - restore_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
      - run:
          name: npm ci
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
      - save_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run prod
      - run:
          name: archive artifacts
          command: zip -ryq laravel-ci.zip .
      - aws-cli/install
      - run:
          name: upload artifacts to s3
          command: aws s3 cp laravel-ci.zip s3://${AWS_S3_BUCKET_NAME}
      - run:
          name: deploy to prod
          command: |
            aws deploy create-deployment \
            --application-name laravel-ci \
            --deployment-group-name laravel-ci \
            --s3-location bucket=${AWS_S3_BUCKET_NAME},key=laravel-ci.zip,bundleType=zip

orbs:
  aws-cli: circleci/aws-cli@1.0.0
  # ここまではCodeDeploy使用時に追加
workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master